//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommUtils.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommUtils.Data.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确认已匹配报关 的本地化字符串。
        /// </summary>
        public static string ConfirmedDeclareCustoms {
            get {
                return ResourceManager.GetString("ConfirmedDeclareCustoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清关延误 的本地化字符串。
        /// </summary>
        public static string CustomsDelay {
            get {
                return ResourceManager.GetString("CustomsDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customs list 的本地化字符串。
        /// </summary>
        public static string CustomsList {
            get {
                return ResourceManager.GetString("CustomsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转运单Excel 的本地化字符串。
        /// </summary>
        public static string DeclaredCustomsList {
            get {
                return ResourceManager.GetString("DeclaredCustomsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报关状态 的本地化字符串。
        /// </summary>
        public static string DeclareStatus {
            get {
                return ResourceManager.GetString("DeclareStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除拣货明细 的本地化字符串。
        /// </summary>
        public static string DeletePickDetail {
            get {
                return ResourceManager.GetString("DeletePickDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除拣货主单 的本地化字符串。
        /// </summary>
        public static string DeletePickParent {
            get {
                return ResourceManager.GetString("DeletePickParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除收货子单 的本地化字符串。
        /// </summary>
        public static string DeleteReceiveDetail {
            get {
                return ResourceManager.GetString("DeleteReceiveDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除统一称重订单 的本地化字符串。
        /// </summary>
        public static string DeleteUniteWeighingOrder {
            get {
                return ResourceManager.GetString("DeleteUniteWeighingOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑拣货单 的本地化字符串。
        /// </summary>
        public static string EditPickParent {
            get {
                return ResourceManager.GetString("EditPickParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑报关单 的本地化字符串。
        /// </summary>
        public static string EditProductShiftCustomset {
            get {
                return ResourceManager.GetString("EditProductShiftCustomset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string ImportBatchOrders {
            get {
                return ResourceManager.GetString("ImportBatchOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调拨跟踪号导入 的本地化字符串。
        /// </summary>
        public static string ImporterTraceCode {
            get {
                return ResourceManager.GetString("ImporterTraceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清关状态 的本地化字符串。
        /// </summary>
        public static string IsCustomsDelay {
            get {
                return ResourceManager.GetString("IsCustomsDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清单扫描管理 的本地化字符串。
        /// </summary>
        public static string ListScanManage {
            get {
                return ResourceManager.GetString("ListScanManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号 的本地化字符串。
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单状态 的本地化字符串。
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拣货管理 的本地化字符串。
        /// </summary>
        public static string PickManage {
            get {
                return ResourceManager.GetString("PickManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮递方式 的本地化字符串。
        /// </summary>
        public static string PostType {
            get {
                return ResourceManager.GetString("PostType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打印PKG 的本地化字符串。
        /// </summary>
        public static string PrintPkg {
            get {
                return ResourceManager.GetString("PrintPkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调拨单管理 的本地化字符串。
        /// </summary>
        public static string ProductShiftManage {
            get {
                return ResourceManager.GetString("ProductShiftManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调拨收货管理 的本地化字符串。
        /// </summary>
        public static string ProductShiftReceiveManage {
            get {
                return ResourceManager.GetString("ProductShiftReceiveManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收货管理 的本地化字符串。
        /// </summary>
        public static string ReceiveManage {
            get {
                return ResourceManager.GetString("ReceiveManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报损 的本地化字符串。
        /// </summary>
        public static string Reportedloss {
            get {
                return ResourceManager.GetString("Reportedloss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报损状态 的本地化字符串。
        /// </summary>
        public static string ReportedlossStatus {
            get {
                return ResourceManager.GetString("ReportedlossStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少选择一项进行操作! 的本地化字符串。
        /// </summary>
        public static string SelectLeastOne {
            get {
                return ResourceManager.GetString("SelectLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移交渠道 的本地化字符串。
        /// </summary>
        public static string SendToChannel {
            get {
                return ResourceManager.GetString("SendToChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发货状态 的本地化字符串。
        /// </summary>
        public static string SentStatus {
            get {
                return ResourceManager.GetString("SentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置分箱跟踪号 的本地化字符串。
        /// </summary>
        public static string SetBoxTraceCode {
            get {
                return ResourceManager.GetString("SetBoxTraceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置邮递方式/重量 的本地化字符串。
        /// </summary>
        public static string SetPostTypeId {
            get {
                return ResourceManager.GetString("SetPostTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置发货 的本地化字符串。
        /// </summary>
        public static string SetSent {
            get {
                return ResourceManager.GetString("SetSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置跟踪号 的本地化字符串。
        /// </summary>
        public static string SetTraceCode {
            get {
                return ResourceManager.GetString("SetTraceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置跟踪号/备注 的本地化字符串。
        /// </summary>
        public static string SetTraceId {
            get {
                return ResourceManager.GetString("SetTraceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物流管理系统V2.0 的本地化字符串。
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OA系统 的本地化字符串。
        /// </summary>
        public static string SystemOA {
            get {
                return ResourceManager.GetString("SystemOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟踪号 的本地化字符串。
        /// </summary>
        public static string TraceCode {
            get {
                return ResourceManager.GetString("TraceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟踪号格式不匹配 的本地化字符串。
        /// </summary>
        public static string TraceIdFormatNotMatch {
            get {
                return ResourceManager.GetString("TraceIdFormatNotMatch", resourceCulture);
            }
        }

        /// <summary>
        /// 请联系产品专员或IT检查跟踪号格式
        /// </summary>
        public static string CallItCheckPost => " 请联系产品专员或IT检查跟踪号格式!";
        
        /// <summary>
        ///   查找类似 承运详情 的本地化字符串。
        /// </summary>
        public static string TransInfo {
            get {
                return ResourceManager.GetString("TransInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调拨单尚未匹配报关 的本地化字符串。
        /// </summary>
        public static string UndeclaredCustoms {
            get {
                return ResourceManager.GetString("UndeclaredCustoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量 的本地化字符串。
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
